steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/student-assignment-program/sap-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/student-assignment-program/sap-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'student-assignment-program', '--image', 'gcr.io/student-assignment-program/sap-image', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated']
images:
       - gcr.io/student-assignment-program/sap-image