version: '3'
services:
  app:
    build:
      context: .
    #command: bash -c "rm -f tmp/pids/server.pid && cron && bundle exec puma -C config/puma.rb"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:11.6
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: sap
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    stdin_open: true

volumes:
  bundle:
    driver: local
