version: '3'
services:
  web:
    build:
      context: ./docker/nginx
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'

volumes:
  bundle:
    driver: local
